<?php

namespace src;

use Illuminate\Support\ServiceProvider;

class FeishuServiceProvider extends ServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
